# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-09 09:53
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_auto_20230608_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='\u0418\u043c\u044f')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('created', '\u0421\u043e\u0437\u0434\u0430\u043d\u043e'), ('sent', '\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e'), ('opened', '\u041e\u0442\u043a\u0440\u044b\u0442\u043e')], default='created', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malings', to='mails.Mailing', verbose_name='\u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0430')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=254, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(related_name='recipients', to='mails.Contact', verbose_name='\u041f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u0438'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='mails.EmailTemplate', verbose_name='\u0428\u0430\u0431\u043b\u043e\u043d'),
        ),
    ]
