# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-11 09:25
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mails', '0003_auto_20230609_0953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OutgoingEmails',
            new_name='OutgoingEmail',
        ),
        migrations.AddField(
            model_name='mailing',
            name='created_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u0435\u043c \u0441\u043e\u0437\u0434\u0430\u043d\u0430'),
            preserve_default=False,
        ),
    ]
