# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-11 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0005_auto_20230611_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='delay_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
