# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-11 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0006_mailing_delay_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingemail',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
