# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-12 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0007_outgoingemail_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingemail',
            name='token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
