# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-14 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0008_outgoingemail_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outgoingemail',
            options={'verbose_name': '\u041f\u0438\u0441\u044c\u043c\u043e', 'verbose_name_plural': '\u041f\u0438\u0441\u044c\u043c\u0430'},
        ),
    ]
